---
- hosts: "servers"
  any_errors_fatal: True
  vars:
    ansible_ssh_private_key_file: "{{ ssh_key_folder|default('~/.ssh') }}/{{ ssh_key_name }}"


  tasks:

    - name: Check if any version of agent is already installed
      stat: path=/usr/sbin/zabbix_agentd
      register: zabbix_agent_installed

    - name: remove zabbix-agent
      become: yes
      action: apt name=zabbix-agent state="absent"
      with_items:
        - zabbix-agent
      when: zabbix_agent_installed.stat.exists

    - name: Download Zabbix Ubuntu 14 (Trusty) release deb file
      get_url:
        url="http://repo.zabbix.com/zabbix/3.4/ubuntu/pool/main/z/zabbix/zabbix-agent_3.4.9-1+trusty_amd64.deb"
        dest="/tmp/zabbix-agent.deb"
      when: ansible_os_family == "Debian" and ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int == 14

    - name: Download Zabbix Ubuntu 16 (Xenial) release deb file
      get_url:
        url="http://repo.zabbix.com/zabbix/3.4/ubuntu/pool/main/z/zabbix/zabbix-agent_3.4.9-1+xenial_amd64.deb"
        dest="/tmp/zabbix-agent.deb"
      when: ansible_os_family == "Debian" and ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int == 16

    - name: install zabbix-agent
      become: yes
      apt: deb="/tmp/zabbix-agent.deb"
      when: ansible_os_family == "Debian"


    # - name: Create log directory
    #   file: path=/var/log/zabbix state=directory owner=zabbix group=zabbix mode=0775
    #   when: not zabbix_agent_installed.stat.exists

    - name: "Backup origin zabbix_agentd.conf"
      copy:
        src: "/etc/zabbix/zabbix_agentd.conf"
        dest: "/etc/zabbix/zabbix_agentd.conf-backup-by-ansible"
        force: yes
        remote_src: yes
      become: yes

    - name: "save zabbix_agentd.conf as config-file"
      copy:
        src: "zabbix_agentd.conf"
        dest: "/etc/zabbix/zabbix_agentd.conf"
        force: yes
      become: yes

    - name: Set hostname on conf file
      become: yes
      lineinfile:
        dest: /etc/zabbix/zabbix_agentd.conf
        regexp: ^Hostname=.*
        insertafter: ^# Hostname=
        line: Hostname={{ inventory_hostname }}

    - name: Unmask zabbix-agent
      ignore_errors: yes
      become: yes
      command: systemctl unmask zabbix-agent.service


    - name: reload zabbix configuration
      become: yes
      service:
        name: zabbix-agent
        state: restarted

    # - name: Start Zabbix agent service
    #   service: name=zabbix-agent state=started enabled=yes
    #   ignore_errors: yes
    #   register: zabbix_service

    # - name: Start Zabbix agent if service module fails
    #   shell: pgrep zabbix_agentd || /usr/sbin/zabbix_agentd
    #   when: zabbix_service|failed