---
- hosts: "{{ host }}"
  serial: 100%
  any_errors_fatal: True
  vars:
    ansible_ssh_private_key_file: "{{ ssh_key_folder|default('~/.ssh') }}/{{ ssh_key_name }}"

  tasks:
    - shell: "/bin/cat /etc/hostname"
      register: host_name

    - debug:
        var: host_name["stdout"]

